# Request

# Relative angle (radians) for robot to rotate along arc from current heading
float32 angle
# Radius of arc (meters) for robot to drive along
float32 radius
# Max rotation speed (positive rad/s), will cap negative angle to negative speed
float32 max_rotation_speed 1.9
---
# Result
# Pose where robot finished
geometry_msgs/PoseStamped pose
---
# Feedback
